resources:
  repositories:
    - repository: templates
      type: github
      name: bincrafters/templates
      endpoint: github

extends:
  template: azure-template.yml
  parameters:
    conanLoginUsername: $(CONAN_LOGIN_USERNAME)
    conanPassword: $(CONAN_PASSWORD)
    collectionsBasePath: "recipes"
    conanUploadOnlyWhenStable: "false"
    # TODO: We still need a custom logic for uploading python_requires, extend bincrafters-package-tools or cpt?
    collectionsProvideAsPythonRequires:
      path: 'recipes\llvm-common\'
      reference: 'llvm-common/0.0.0@Manu343726/testing'
    collectionsStages:
      - "G1"
      - "G2"
    collectionsRecipes:
      - name: 'llvm_headers'
        stage: 'G1'
        type: 'header_only'
      - name: 'llvm'
        stage: 'G1'
        type: 'library'
      - name: 'compiler-rt'
        stage: 'G2'
        type: 'library'
