resources:
  repositories:
    - repository: templates
      type: github
      name: bincrafters/templates
      endpoint: github

jobs:
- template: azure-template.yml
  parameters:
    conanLoginUsername: $(CONAN_LOGIN_USERNAME)
    conanPassword: $(CONAN_PASSWORD)
    splitByBuildTypes: "true"
    collectionsRecipes: 
      - name: ""
      - directory: "."     
